site_name: algobase

theme:
  name: "material"
  features:
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            unwrap_annotated: true

nav:
  - Welcome: index.md
  - How-To Guides:
      - How to Validate ARC-3 Assets and Metadata: how_to/how_to_validate_arc3.md
      - How to Store JSON in IPFS: how_to/how_to_store_json_ipfs.md
      - How to Mint an NFT on LocalNet: how_to/how_to_mint_nft_localnet.md
  - Reference:
      - Reference: reference.md
